### ISSUE TITLE
you might ease guessing country names

### ISSUE THREAD

**Issue by czyborra** [paroj/arewedeadyet#6]
Since "England" "Great Britain" "United States" are all regarded as unknown countries, you might want to add the well-defined https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Decoding_table as aliases, might you not?

**Comment by paroj** [comment]
currently, I am perely parsing this file: https://pomber.github.io/covid19/timeseries.json (preferrably ope in firefox)
Also, implementing auto-completion would improve usability more IMO. As the current state sufficiently serves me, I leave this for pull-request.

**Comment by paroj** [comment]
fixed
